platform :ios, '9.0'
target 'MyTestApp' do
  inherit! :search_paths
  use_frameworks!
  pod 'CAIStatusBar', '~> 0.0.1'
  pod 'CWNotificationBanner', '~> 0.1.1'
  pod 'AKTransmission', '~> 0.1.1'
  pod 'ESThread', '~> 0.1.2'
  pod 'MDFRobotoFontLoader'
  pod 'XPieChart'
  pod 'OpenGraph'
  pod 'PokeDexLib'
  pod 'QLSLogger'
  pod 'NZGoogleAnalytics'
  pod 'BMSGoogleAuthentication'
  pod 'LHSKeyboardAdjusting'
  pod 'SwiftLocalization'
  pod 'TWCategory'
  pod 'libGitHubIssues', '0.0.1'
  pod 'VisualSwift', '> 0.1.2'
  pod 'CCBottomRefreshControl', '0.4'
  pod 'KSReachability', '>= 1.3'
  pod 'ParallaxHeaderView', '<= 0.1.1'
  pod 'TRVSEventSource', '< 0.0.8'
  pod 'DelegateProxy', :git => 'https://github.com/ra1028/DelegateProxy.git'
  pod 'SongtreeSDK',  :git => 'https://github.com/SongtreeSDK/Songtree.git', :commit => 'dc606197a5'
  pod 'Holarchy','0.0.5'
  pod 'CancellationToken','0.2.0'
end
